- name: Delete zookeeper
  file:
    path: "{{ ZOOKEEPER_HOME }}"
    state: absent
    owner: root

- name: Delete zookeeper data dir
  file:
    path: "{{ ZOOKEEPER_DATA_DIR }}"
    state: absent
    owner: root

- name: Delete zookeeper log dir
  file:
    path: "{{ ZOOKEEPER_LOG_DIR }}"
    state: absent
    owner: root
