- name: "Create hadoop {{item}} directory."
  file: path={{item}} state=directory owner=root group=root
  with_items:
    - "{{data_dir}}"
    - "{{dfs_dn_dir}}"
    - "{{dfs_nn_dir}}"
    - "{{log_dir}}"
    - "{{qjournal_dir}}"
    - "{{hadoop_conf_dir}}"
    - "{{socket_dir}}"
    - "{{yarn_app_log_dir}}"
    - "{{yarn_data_local}}"
    - "{{yarn_data_log}}"
    - "{{log_dir}}/hadoop-hdfs"

- name: Gather ec2 facts
  ec2_facts:
  register:
    ec2s

- name: debug
  debug: 
    msg: "{{hostvars[item]}}"
  with_items: "{{ groups['zookeepers'] }}"

- name: Configure hadoop
  template: 
    src: "{{ item }}"
    dest: "{{HADOOP_HOME}}/conf/{{ item }}" 
    owner: root 
    group: root 
    mode: 0644
  with_items:
    - core-site.xml
    - hadoop-env.sh
    - hadoop-metrics2.properties
    - hdfs-site.xml
    - org-xerial-snappy.properties
    - slaves
    - mapred-site.xml
    - yarn-site.xml
    - fair-scheduler.xml
    - dfs.hosts.exclude
    - httpfs-site.xml
    - httpfs-env.sh
    - httpfs-signature.secret

