- name: Install open-jdk
  yum:
    name: java-1.8.0-openjdk-devel
    state: present

- name: Install nc
  yum:
    name: nc
    state: present

- name: Download KAFKA Tar
  get_url:
    url: "{{ KAFKA_URL }}"
    dest: "{{ INSTALLATION_DIR }}"
    mode: 0644

- name: Unpack Kafka tar
  shell: tar zxvf {{ INSTALLATION_DIR }}/{{ KAFKA_TAR }} -C {{ INSTALLATION_DIR }}

- name: Remove Kafka tar
  file:
    path: "{{ INSTALLATION_DIR }}/{{ KAFKA_TAR }}"
    owner: root
    state: absent

- name: Move kafka-{{ KAFKA_VERSION }} to kafka
  shell: mv {{ INSTALLATION_DIR }}/kafka_{{ SCALA_VERSION }}-{{ KAFKA_VERSION }} {{ INSTALLATION_DIR }}/kafka

- name: Create kafka data directory
  file:
    path: "{{ KAFKA_DATA_DIR }}"
    state: directory
    owner: root
    mode: 0644

- name: Create Kafka log directory
  file:
    path: "{{ KAFKA_LOG_DIR }}"
    state: directory
    owner: root
    mode: 0644

- name: Create zookeeper data directory
  file:
    path: "{{ ZOOKEEPER_DATA_DIR }}"
    state: directory
    owner: root
    mode: 0644

- name: Create Kafka log directory
  file:
    path: "{{ ZOOKEEPER_LOG_DIR }}"
    state: directory
    owner: root
    mode: 0644
