---

- name: Get running EC2 instances for the given tag
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ tag_key_vals.Name }}"
      instance-state-name: running
  register: ec2_info

- name: Dissociate and release EIPs associated with instances
  ec2_eip:
    state: absent
    region: "{{ region }}"
    device_id: "{{ item.id }}"
    release_on_disassociation: True
  with_items: "{{ ec2_info.instances }}"

- name: Stop EC2 instances specified by the given tag
  ec2:
    state: 'absent'
    region: "{{ region }}"
    wait: True
    instance_ids: "{{ item.id }}"
  with_items: "{{ ec2_info.instances }}"